defaults: &defaults
  site_name: 'Clipclap(Î²)'
  page: 25
  ranking_limit: 50
  thumb_width: 240
  thumb_format: 'jpg'
  html_cache_dir: '/tmp/clipclap/html_cache'
  image_cache_dir: '/tmp/clipclap/image_cache'
  maximum_tag_count: 10
  maximum_comment_count: 10
  minimum_image_width: 16
  minimum_image_height: 16
  allowed_image_aspect: [ 16, 3 ]
  facebook_id: '520109864725351'
  facebook_key: 'd56427de565d1fbc5d7f2268063c4a30'
  mixi_key: '138755f57dd15996cafaf13177bb1d70114b1760'
  twitter_id: 'TrZTve5b1xwZaxBD8AB3Q'

development:
  <<: *defaults
  page: 10
  html_cache_dir: <%= File.join(Rails.root, 'tmp', 'html_cache') %>
  image_cache_dir:  <%= File.join(Rails.root, 'tmp', 'image_cache') %>

test:
  <<: *defaults

production:
  <<: *defaults
