defaults: &defaults
  page: 70
  thumb_width: 180
  html_cache_dir: <%= File.join(Rails.root, 'tmp', 'html_cache') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
