defaults: &defaults
  site_name: 'Clipclap(Î²)'
  page: 50
  ranking_limit: 50
  thumb_width: 240
  html_cache_dir: <%= File.join(Rails.root, 'tmp', 'html_cache') %>
  image_cache_dir:  <%= File.join(Rails.root, 'tmp', 'image_cache') %>
  maximum_tag_count: 10
  maximum_comment_count: 10
  minimum_image_width: 16
  minimum_image_height: 16
  allowed_image_aspect: [ 16, 5 ]

development:
  page: 25
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
